name: Deploy to Oracle VM

on:
  push:
    branches:
      - feature_architecture  # ou o branch que você quiser monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'  # Versão do JDK que você está usando

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: SCP to Oracle VM
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa -P ${{ env.PORT }} target/*.jar ${{ env.USERNAME }}@${{ env.HOST }}:/home/ubuntu/workflow
