name: Deploy to Oracle VM

on:
  push:
    branches:
      - feature_architecture

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Verify JAR file
        run: |
          ls -lh ./target/pets4ever-0.0.1-SNAPSHOT.jar

      - name: SCP to Oracle VM
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            PORT: ${{ secrets.SSH_PORT }}
            HOST: ${{ secrets.SSH_HOST }}
            USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
            echo "$PRIVATE_KEY" | base64 --decode > /tmp/id_rsa
            chmod 600 /tmp/id_rsa
            scp -i /tmp/id_rsa -P $PORT ./target/pets4ever-0.0.1-SNAPSHOT.jar $USERNAME@$HOST:/home/$USERNAME/workflow/
